name: CD_deploy_super_app
# Controls when the workflow will run
on:
  push:
    branches: [master]
  # Triggers the workflow on push or pull request events but only for the "master" branch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # przygotowujemy środowisku
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0 # w danej wersji
      - name: Restore dependences # robimy restore
        run: dotnet restore
      - name: Build #potem builda
        run: dotnet build --no-restore
      - name: Publish  #pulikujmey app do odpowiedniego folderu uzywajac zminnej root tak aby polecenie bylo niezalezne od wykonywanego środowiska
        run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/myFolder
      - name: upload artifact # zipujemy porjekt
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: personsApi-artifact
          path: ${{ env.DOTNET_ROOT }}/myFolder


  deploy-prod: # kolejny job dla sorodiwska produkcyjnego 
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: 'Prod'  # okreslanmy jak sie nazywa środowisko 
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }} #okreslamy url aplikacji (Azure WebApp)
    steps: 
      - name: Download a Build Artifact #pobieramy zipa
        uses: actions/download-artifact@v3.0.0
        with: 
          name: personsApi-artifact
      - name: Azure WebApp #uploadujemy do Azure
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2 
        with: 
          app-name: 'alxshopapi' # nazwa aplikacji w azure
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }} #uzywamy secrets przchowujacy profil publikacji 
